### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by luiarthur** [luiarthur/Boggle-scala-js#4]
- [ ] Redo this project in Typescript + React with the following improvements
    - [x] Provide a board
    - [x] Provide solutions
    - [ ] Play with other users using Firebase authentication
    - [ ] Allow users to enter their solution (using finger swipes)
    - [ ] Provide option (mode) to check if word is valid
    - [ ] Allow custom dictionary submissions
